build:
  image: minimum2scp/sphinx
  commands:
    - sudo make html

publish:
  sftp:
    host: 10.10.0.186
    port: 22
    username: www-data
    destination_path: /var/www/docs.freifunk-hennef.de/
    files: 
      - build/html/*
