build:
  image: minimum2scp/sphinx
  commands:
    - sudo make html

publish:
  sftp:
    host: 2a01:4f8:150:4426::9999:17
    port: 22
    username: www-data
    destination_path: /var/www/docs.freifunk-hennef.de/
    files: 
      - build/html/*
