pipeline:
  build:
    image: minimum2scp/sphinx
    commands:
      - sudo make html

  deploy:
    image: drillster/drone-rsync
    hosts: [ "10.10.0.186" ]
    user: www-data
    key: ${DEPLOYKEY}
    source: /tmp/build/html/
    target: /var/www/docs.freifunk-hennef.de/
    delete: false
    recursive: true

