build:
  image: minimum2scp/sphinx
  commands:
    - sudo make html

deploy:
  rsync:
    user: www-data
    host: 10.10.0.186
    port: 22
    source: build/html/
    target: /var/www/docs.freifunk-hennef.de/
    delete: true
    recursive: true
