pipeline:
  build:
    image: minimum2scp/sphinx
    commands:
      - sudo make html

deploy:
  rsync:
    image: drillster/drone-rsync
    user: www-data
    hosts: [ "10.10.0.186" ]
    key: ${DEPLOYKEY}
    source: build/html/
    target: /var/www/docs.freifunk-hennef.de/
    delete: false
    recursive: true

